ecommerce/ecommerceproject/cart_app/urls.py
from django.urls import path
from .import views

app_name='cart_app'

urlpatterns=[
      path('', views.cart_detail, name='cart_detail'),
      path('add/<int:product_id>', views.add_cart, name='add_cart'),
      path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
      path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerce/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp', include('shopapp.urls')),
    path('search_app/', include('search_app.urls')),
    path('cart_app/', include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns=[
      path('',views.search_result,name='search_result'),
]

ecommerce/ecommerceproject/shopapp/urls.py
from . import views
from django.urls import path

app_name = 'shopapp'

urlpatterns = [
    path('', views.allCategory, name='allCategory'),
    path('<slug:c_slug>/', views.allCategory, name='allCategory1'),
    path('<slug:c_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),

]

ecommerce/ecommerceproject/cart_app/models.py
from django.db import models
from shopapp.models import Product


# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/ecommerceproject/shopapp/models.py
from django.db import models

from django.urls import reverse


# Create your models here.
class category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shopapp:allCategory1', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product')
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shopapp:product_detail', args=[self.category.slug, self.slug])

ecommerce/ecommerceproject/cart_app/views.py
from shopapp.models import Product
from .models import Cart, CartItem
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart_app:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return  redirect('cart_app:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_detail')

ecommerce/ecommerceproject/search_app/views.py
# import operator
# from functools import reduce

from django.db.models import Q
from django.shortcuts import render
from shopapp.models import Product


# Create your views here.

def search_result(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        # q_list = [Q(name__contains=query), Q(description__contains=)]
        # Product.objects.filter(reduce(operator.or_, q_list))
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', {'query': query, 'products': products})

ecommerce/ecommerceproject/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import category, Product
from django.core.paginator import EmptyPage, InvalidPage, Paginator


# Create your views here.
def allCategory(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'products': products})


def product_detail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce/ecommerceproject/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link href="{%static '/css/custom.css' %}" rel="stylesheet">
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription%}{%endblock%}"
    <title>{% block title%}{%endblock%}</title>
</head>
<body>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="{% static 'js/popper.min.js'%}" ></script>
<script src="{%static 'js/bootstrap.min.js'%}" ></script>
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}

</body>
</html>

ecommerce/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is the cart page. proceed to review your items and place the order.
{% endblock %}
{%block title%}
  Cart
{%endblock%}
{%block content%}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping cart is empty!
        </h1>
        <br>
        <p clas="text-center">
          Please Click<a href="{% url 'shopapp:allCategory'%}">here</a> to continue shopping
        </p>

    </div>
</div>
{%else%}
<div>
    <div class="text-center">
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>
    </div>

    <div class="row mx_auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table>
                <thead class="my_custom_thead">
                <tr>
                    <th colspan="5">
                       Your Items
                    </th>
                </tr>

                </thead>
                <br>
                <tbody>
                {%for cart_item in cart_items%}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;"  class="float-left rounded custom_image custom_image"></a>
                    </td>
                    <td class="text-left">
                        {{cart_item.product.name}}
                        <br>
                        SKU:{{cart_item_product.id}}
                        <br>
                        Price:$ {{cart_item.product.price}}
                        <br>
                        QTY:{{cart_item.quantity}} * $ {{cart_item}}

                    </td>
                    <td>
                        $ {{cart_item.sub_total}}
                    </td>
                    {% if cart_item.quantity < cart_item.product.stock %}
                    <td>
                        <a href="{% url 'cart_app:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus-circle" ></i></a>&nbsp;
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}"><i class="fa fa-minus-circle custom_icon" ></i></a>
                        &nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}"><i class="fa fa-trash custom_icon" ></i></a>
                    </td>
                    {%else%}
                    <td>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' cart_item.product.id %}"><i class="fa fa-minus-circle custom_icon" ></i></a>
                        &nbsp;&nbsp;<a href="{% url 'cart_app:full_remove' cart_item.product.id %}"><i class="fa fa-trash custom_icon" ></i></a>
                    </td>
                    {%endif%}
                </tr>
                {%endfor%}
                </tbody>

            </table>

        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_custom_table">
                <thead class="my_custom_thead">
                <tr>
                    <th>
                        Checkout
                    </th>
                </tr>
                </thead>
                <br>
                <tbody>
                <tr>
                    <td>
                        Please review your shopping cart items before proceeding with order payment
                    </td>
                </tr>
                <tr>
                    <td class="text-left">
                        SubTotal:<strong>{{total}}</strong>

                    </td>
                </tr>
                </tbody>

            </table>
            <div class="mx_auto">
                <a href="{% url 'shopapp:allCategory'%}" class="btn btn-secondary btn-block my_custom_table">Continue Shopping</a>

            </div>

        </div>

    </div>
</div>
{% endif %}
{% endblock %}

ecommerce/ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
    {{category.description|truncatewords:150}}
   {% else %}
    Welcome to ABC Stores where u can buy everything you need!
   {%endif%}
{% endblock %}
{% block title %}
{% if category %}
    {{category.name}}-ABC Store
   {% else %}
   See our new collections-ABC Store
   {% endif %}
{% endblock %}
{% block content %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx_auto">
        <p><a href="{%url 'shopapp:allCategory' %}">Our Product Collections</a></p>
    </div>
        </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <img class="my_image" src="{{category.img.url}}" alt="{{category.name}}">
</div>
<br/>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>

</div>
{% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'image/banner.png'%}" alt="our products" width="1250px">
</div>
<br>
<div>
    <h1 class="text-center my_title">our products collection</h1>
    <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer eu orci accumsan, placerat felis id, rutrum nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc metus ex, lobortis ac massa et, vestibulum ullamcorper neque. Phasellus mauris mi, pulvinar ultricies ipsum et, viverra pulvinar nisl. In id lectus at mi ultricies scelerisque. Praesent consectetur leo ante, quis fermentum augue feugiat vitae. Donec fringilla laoreet consectetur. </p>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
    {% for product in products.object_list %}
    <div class="my_bottom_margin col-sm-12 col-md-4  xol-lg-4">
        <div class="card text-center" style="min-width:18rem;">
            <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
       <div class="card-body">
           <h4>{{product.name}}</h4>
               <p>{{product.price}}</p>
       </div>

        </div>
    </div>
    {% endfor %}
        </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>
        <div class="text-center">
            {%for pg in products.paginator.page_range%}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
         {% endif %}
    </div>
    <br/>
</div>
{% endblock %}

ecommerce/ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">
        @COPYRIGHT;ABC PRIVATE LTD.All rights received
    </p>
</div>

ecommerce/ecommerceproject/templates/header.html
{%load static%}
<header>
    <center>
    <a href="{%url 'shopapp:allCategory'%}" ><img src="{%static 'image/logo.png'%}" alt="logoimage"></a>
    </center>
</header>

ecommerce/ecommerceproject/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="#">Shop</a>
        </li>
        <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shopapp:allCategory'%}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}

          </ul>
        </li>
        {% if item_count > 0%}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'cart_app:cart_detail' %}"><i class="fa fa-shopping-cart">({{item_count}})</i></a>
        </li>
        {%endif%}
      </ul>
      <form class="d-flex" action="{% url 'search_app:search_result' %}" method="get">
        {%csrf_token%}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {{product.description|truncatewords:150}}

{% endblock %}
{% block title %}

    {{product.name}}-ABC Store


{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shopapp:allCategory' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category.name}}</a> |{{product.name}}</p>
    </div>
</div>
<br>
<div class="container">
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}" class="custom_image">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
    <h1 class="my_prod_title">{{product.name}}</h1>
        <p>{{product.price}}</p>
        <p class="my_title"><b>Product Description</b></p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
        {% else %}
        <a class="btn btn-secondary" href="{% url 'cart_app:add_cart' product.id %}">Add to Cart</a>
        {% endif %}

    </div>
</div>
    </div>
</div>
{% endblock %}

ecommerce/ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of yummy products available
{% endblock %}
{%block title%}
search
{%endblock%}
{%block content%}
<div>
    <p class="text-center my_search_text">you have searched for :<b>"{{query}}"</b></p>
</div>
   <div class="container">
     <div class="row mx_auto">
       {% for product in products %}
        <div class="my_bottom_margin col-9 col-md-4  col-lg-4">
           <div class="card text-center" style="min-width:18rem;">
              <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" style="width:285px;height:350px;color:black;"></a>
               <div class="card-body">
                   <h4>{{product.name}}</h4>
                   <p>${{product.price}}</p>
               </div>

           </div>
        </div>
         {%empty%}
         <div class="row mx_auto">
             <p class="text-center my_search_text">0 results found</p>

         </div>
      {% endfor %}
     </div>
   </div>
{%endblock%}